name: huntervsspeedrunner
version: '1.10-release'
main: me.example.huntervsspeedrunner.HunterVSSpeedrunnerPlugin
api-version: '1.20'
authors: [FLINGO]
description: "Plugin for the Hunter vs Speedrunner game"
commands:
  hunter:
    description: Command to control the Hunter vs Speedrunner game
    usage: "/hunter [start|stop]"
  start:
    description: Start the game
    usage: "/hunter start"
    permission-message: "Only operators can start the game."
  stop:
    description: End the game
    usage: "/hunter stop"
    permission-message: "Only operators can stop the game."
  hunterworld:
    description: Execute commands for the world
    usage: "/hunterworld"
    permission-message: "You do not have permission to execute this command."
